id: lancepilot_followup
namespace: company.team
description: "Worker Agendado (Cron) para processar Follow-ups do LancePilot (SaaS)."

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"

tasks:
  - id: run_followup_worker
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    containerImage: marsllator/my-kestra-worker:latest
    
    namespaceFiles:
      enabled: true
      include: [ "**" ]

    commands:
      - rm -f .env
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/lancepilot/followup_worker.py
    
    env:
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      GEMINI_API_KEY: "{{ kv('GEMINI_API_KEY') }}"
