id: metrics_aggregation
namespace: company.team
description: "Agrega eventos de conversa em métricas diárias (ADR-003). Roda a cada 5 minutos."

# Evita múltiplas execuções simultâneas
concurrency:
  limit: 1
  behavior: CANCEL

triggers:
  - id: every5min
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"
    timezone: America/Sao_Paulo

tasks:
  - id: aggregate_metrics
    type: io.kestra.plugin.scripts.python.Commands

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
    containerImage: marsllator/kestra-api-manager:latest

    namespaceFiles:
      enabled: true
      include:
        - "Kestra_2.0/scripts/shared/**"

    commands:
      - rm -f .env
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/shared/metrics_worker.py

    env:
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
