id: reminders
namespace: company.team
description: Processa lembretes pendentes a cada 5 minutos e envia via Uazapi com análise de contexto.

triggers:
  - id: every5min
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"
    timezone: America/Sao_Paulo

# Evita múltiplas execuções simultâneas
concurrency:
  limit: 1
  behavior: CANCEL

tasks:
  - id: process_reminders
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    containerImage: marsllator/kestra-api-manager:latest

    namespaceFiles:
      enabled: true
      include: [ "**" ]

    commands:
      - rm -f .env
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/uazapi/reminder_worker.py

    env:
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
