id: saas_followup_cron
namespace: company.team
description: "Roda a cada 5min para verificar e enviar Follow-ups de WhatsApp (SaaS)"

# ⚠️ Para desativar COMPLETAMENTE este flow, comente o trigger ou delete o flow do Kestra UI

# Concurrency para evitar overlap de execuções
concurrency:
  limit: 1
  behavior: CANCEL  # Se já está rodando, cancela nova execução

tasks:
  - id: run_followup_worker
    type: io.kestra.plugin.scripts.python.Commands
    pythonVersion: "3.11"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
    containerImage: marsllator/kestra-api-manager:latest
    
    namespaceFiles:
      enabled: true
      include: ["**"]
    
    beforeCommands:
      - pip install cryptography > /dev/null 2>&1

    commands:
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/uazapi/followup_worker.py

    env:
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
      GEMINI_API_KEY: "{{ kv('GEMINI_API_KEY') }}"
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      UAZAPI_URL: "{{ kv('UAZAPI_URL') }}"
      UAZAPI_KEY: "{{ kv('UAZAPI_KEY') }}"
      OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
      OPENROUTER_API_KEY: "{{ kv('OPENROUTER_API_KEY') }}"
      ENCRYPTION_KEY: "{{ kv('ENCRYPTION_KEY') }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"

