id: uazapi_pure_native2
namespace: company.team
description: Fluxo Puro NATIVO Kestra (Otimizado com Imagem Custom).

# ⚡ CONTROLE DE CONCORRÊNCIA - Evita esgotar conexões do PostgreSQL
concurrency:
  limit: 10  # Máximo de 10 execuções simultâneas (ajuste conforme necessário)
  behavior: QUEUE  # Webhooks extras vão para fila ao invés de serem rejeitados

inputs:
  - id: message
    type: JSON
    description: Payload Webhook

tasks:

  # -------------------------------------------------------------------------
  # TASK 1: INGESTÃO E BUFFER
  # -------------------------------------------------------------------------
  - id: ingest_task
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    containerImage: marsllator/kestra-api-manager:latest

    namespaceFiles:
      enabled: true
      include: [ "**" ]

    commands:
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/uazapi/ingest.py

    env:
      KESTRA_TRIGGER_BODY: "{{ (inputs.message ?? trigger.body ?? {}) | json }}"
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      UAZAPI_URL: "{{ kv('UAZAPI_URL') }}"
      UAZAPI_KEY: "{{ kv('UAZAPI_KEY') }}"
      GEMINI_API_KEY: "{{ kv('GEMINI_API_KEY') }}"
      OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
      BUFFER_KEY_SUFIX: "_buffer"
      BUFFER_TTL: "300"

  - id: debounce
    type: io.kestra.plugin.core.flow.Pause
    delay: PT15S

  # -------------------------------------------------------------------------
  # TASK 3: CÉREBRO (RAG/AI)
  # -------------------------------------------------------------------------
  - id: ai_worker
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    containerImage: marsllator/kestra-api-manager:latest

    namespaceFiles:
      enabled: true
      include: [ "**" ]

    commands:
      - rm -f .env
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/uazapi/rag_worker.py

    env:
      KESTRA_CHAT_ID: "{{ outputs.ingest_task.vars.chat_id ?? 'None' }}"
      KESTRA_CLIENT_TOKEN: "{{ trigger.body.token ?? trigger.body.instanceId ?? 'DEFAULT_TOKEN' }}"
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
      GEMINI_API_KEY: "{{ kv('GEMINI_API_KEY') }}"
      GOOGLE_MAPS_API_KEY: "{{ kv('GOOGLE_MAPS_API_KEY') }}"
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"
      VECTOR_STORE_PATH: "vectorstore"
      RAG_FILES_DIR: "rag_files"
      BUFFER_KEY_SUFIX: "_buffer"

  # -------------------------------------------------------------------------
  # TASK 4: ENVIO (WhatsApp)
  # -------------------------------------------------------------------------
  - id: send_whatsapp
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    containerImage: marsllator/kestra-api-manager:latest

    namespaceFiles:
      enabled: true
      include: [ "**" ]

    commands:
      - rm -f .env
      - export PYTHONPATH=$PYTHONPATH:.
      - python Kestra_2.0/scripts/uazapi/whatsapp_sender.py

    env:
      KESTRA_CHAT_ID: "{{ outputs.ai_worker.vars.chat_id ?? outputs.ingest_task.vars.chat_id ?? 'None' }}"
      KESTRA_RESPONSE_TEXT: "{{ outputs.ai_worker.vars.response_text ?? '' }}"
      KESTRA_API_URL: "{{ outputs.ai_worker.vars.api_url ?? '' }}"
      KESTRA_API_KEY: "{{ outputs.ai_worker.vars.api_key ?? '' }}"
      REDIS_URL: "{{ kv('REDIS_URL') }}"
      UAZAPI_URL: "{{ kv('UAZAPI_URL') }}"
      UAZAPI_KEY: "{{ kv('UAZAPI_KEY') }}"
      OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
      DATABASE_CONNECTION_URI: "{{ kv('DATABASE_URL') }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: uazapigo_native
